### ISSUE TITLE
no module registered on NPM?

### ISSUE THREAD

**Issue by juicycool92** [a-tokyo/micro-geoip-lite-js#1]
Hello,
i tried follow codes
`npm i --save micro-geoip-light `

and got follow errors
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/micro-geoip-light - Not found
npm ERR! 404
npm ERR! 404  'micro-geoip-light@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

same as yarn.

does name changed or something?

Thanks

**Comment by juicycool92** [comment]
found probloms
its `micro-geoip-lite` not `micro-geoip-light`
maybe its typo i guess :>

**Comment by a-tokyo** [comment]
The name of the module is `micro-geoip-light` as it says in the README https://github.com/A-Tokyo/micro-geoip-lite-js#installation 🚀
